services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8000:80

  id-card-service:
    container_name: id-card-service
    build:
      context: ./backend/id-card-service
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./backend/id-card-service:/app

  eureka-service:
    container_name: eureka-service
    build:
      context: ./backend/eureka-service
      dockerfile: Dockerfile
    ports:
      - 8761:8761

  gateway-service:
    container_name: gateway-service
    build:
      context: ./backend/gateway-service
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - EUREKA_DEFAULT_ZONE=http://eureka-service:8761/eureka
    depends_on:
      - eureka-service

  auth-service:
    container_name: auth-service
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/auth-service
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - EUREKA_DEFAULT_ZONE=http://eureka-service:8761/eureka
    depends_on:
      - db
      - eureka-service
      - gateway-service

  db:
    container_name: db
    image: mysql:8
    volumes:
      - ./docker/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: auth-service
